name : Step Types Demo
on: 
  workflow_dispatch: 

jobs: 
  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello World")
        shell: python
  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/greeting-workflow@d8e2f77a33b1833fa8220dd19cbb11009ad81e86
        with:
          who-to-greet : "Azaz"
          
